### ISSUE TITLE
Error in line 6 /usr/share/dnsmasq/trust-anchors.conf

### ISSUE THREAD

**Issue by kingma-sbw** [bshaw/container-dnsmasq#1]
Error in container

`[[qnap-dnsmasq](https://github.com/bqbn/qnap-dnsmasq)](dnsmasq: unsupported option (check that dnsmasq was compiled with DHCP/TFTP/DNSSEC/DBus support) at line 6 of /usr/share/dnsmasq/trust-anchors.conf)`

**Comment by bshaw** [comment]
What specific functionality are you trying to use in your config? The installed dnsmasq is what comes from the default Alpine package (`apk add dnsmasq`) which may not have been compiled with every option you require.

See compiled options in the `dnsmasq --version` output below: 

```bash
❯ podman run -it docker.io/bshaw/dnsmasq dnsmasq --version            
Dnsmasq version 2.89  Copyright (c) 2000-2022 Simon Kelley
Compile time options: IPv6 GNU-getopt no-DBus no-UBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset no-nftset auth no-cryptohash no-DNSSEC loop-detect inotify dumpfile

This software comes with ABSOLUTELY NO WARRANTY.
Dnsmasq is free software, and you are welcome to redistribute it
under the terms of the GNU General Public License, version 2 or 3.
```
